# 系统配置

# 模型路径
QWEN_MODEL_PATH = "Qwen/Qwen2.5-Omni-7B"

# Google搜索API设置
GOOGLE_API_KEY = "YOUR_GOOGLE_API_KEY"
GOOGLE_SEARCH_ENGINE_ID = "YOUR_SEARCH_ENGINE_ID"
GOOGLE_IMAGE_SEARCH_ENGINE_ID = "YOUR_IMAGE_SEARCH_ENGINE_ID"

# RAG设置
VECTOR_DIMENSION = 768
INDEX_PATH = "data/cache/faiss_index"
BATCH_SIZE = 32
TOP_K_RETRIEVAL = 20
TOP_K_RERANK = 5

# 设备设置
DEVICE = "cuda"  # 或 "cpu"

# 缓存设置
CACHE_DIR = "data/cache"
ENABLE_CACHE = True